# =====================================
# 生产环境配置
# =====================================

# 服务器配置
server:
  # 默认端口
  port: 8080
  # 服务器地址
  address: ${SERVER_ADDRESS}

# Spring 配置
spring:
  # SQL数据源配置
  datasource:
    # 数据库连接配置
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    # 数据库用户名
    username: ${DB_USERNAME}
    # 数据库密码
    password: ${DB_PASSWORD}
    # 数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池配置
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 10
      # 连接池最小连接数
      minimum-idle: 5
      # 连接池最大空闲时间
      idle-timeout: 60000
      # 连接池最大等待时间
      connection-timeout: 30000
  # NoSQL 配置
  data:
    # Redis 配置
    redis:
      # Redis 主机地址
      host: ${REDIS_HOST}
      # Redis 端口
      port: ${REDIS_PORT}
      # Redis 密码
      password: ${REDIS_PASSWORD}
      # Redis 数据库索引
      database: ${REDIS_DATABASE}
      # Redis 连接超时时间
      timeout: ${REDIS_TIMEOUT}
      # Redis 连接池配置
      lettuce.pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

# mybatis plus 配置
mybatis-plus:
  # MyBatis 配置项
  configuration:
    # 关闭日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# Sa-Token 配置
sa-token:
  # token 有效期（单位：秒）
  timeout: 2592000
  # token 最低活跃频率（单位：秒）
  active-timeout: -1
  # 输出操作日志
  is-color-log: false
  # JWT 签名密钥
  jwt-secret-key: ${JWT_SECRET_KEY}
